### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by rubgithub** [johankson/awesome#1]
Button not showing image, tested on Android. (downloaded code without modification)

<Button Text="&#xf041;" FontSize="40" FontFamily="FontAwesome" />
<Button Text="{x:Static local:FontAwesome.FAPhone}" FontSize="40" FontFamily="FontAwesome" />

**Comment by rubgithub** [comment]
Not ready.

**Comment by johankson** [comment]
Thanks for the catch. What version of Android?

**Comment by rubgithub** [comment]
Version 5.1.1 and 4.4.  
Should not exists a classe AwesomeRenderer  that implements ButtonRenderer like AwesomeRenderer : LabelRenderer?

**Comment by johankson** [comment]
Yes, yes there should... Very good catch! I have no clue how that slipped through. :) I'll update the code.

**Comment by johankson** [comment]
Closing the issue, fixed on Android as suggested by @rubgithub. Thanks!
