### ISSUE TITLE
Just information, FontAttributes="Bold" (iOS)

### ISSUE THREAD

**Issue by rubgithub** [johankson/awesome#3]
Avoid `FontAttributes="Bold"` on iOS. If this attribute is set, the image will not show.

Tested on iOS 8.4 (simulator)

**Comment by johankson** [comment]
I'm not sure this is an issue, there's no font for Bold in the Awesome typeface. (Hope I'm using the terms correct here). Hence, there is nothing to render. What we could do is to try to remove the usage of the attribute if the text falls into the criteria of being a font awesome char. That would require a renderer on iOS as well though. What's your thoughts?

**Comment by rubgithub** [comment]
In fact, I don't think this is an issue. In my option is enough an observation in the documentation to alert users.
